GET http://localhost:3000/todos/?status=TO%20DO
###
GET http://localhost:3000/todos/1/
###
GET http://localhost:3000/agenda/?date=2021-2-22
###
POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
  "dueDate": "2021-4-12"
}
###
DELETE http://localhost:3000/todos/6/
###
GET http://localhost:3000/todos/?search_q=BUY
###

GET http://localhost:3000/todos/